export const LOADED_BOUNS = 'LOADED_BOUNS'
export const LOAD_MORE_BOUNS = 'LOAD_MORE_BOUNS'

export const LOADED_LATEST_DATA = 'LOADED_LATEST_DATA'

export const LOAD_SEARCH_DATA = 'LOAD_SEARCH_DATA'

export const TOGGLE_THEME = 'TOGGLE_THEME'