export const LOADED_BOUNS = 'LOADED_BOUNS'
export const LOAD_MORE_BOUNS = 'LOAD_MORE_BOUNS'

export const LOADED_LATEST_DATA = 'LOADED_LATEST_DATA'

export const LOAD_SEARCH_DATA = 'LOAD_SEARCH_DATA'

export const TOGGLE_THEME = 'TOGGLE_THEME'

export const LOADED_ANDROID_DATA = 'LOADED_ANDROID_DATA'
export const LOADED_IOS_DATA = 'LOADED_IOS_DATA'
export const LOADED_VIDEO_DATA = 'LOADED_VIDEO_DATA'
export const LOADED_EXPAND_DATA = 'LOADED_EXPAND_DATA'
export const LOADED_FRONTEND_DATA = 'LOADED_FRONTEND_DATA'
export const LOADED_RANDOM_DATA = 'LOADED_RANDOM_DATA'

export const ADD_COLLECTION = 'ADD_COLLECTION'
export const REMOVE_COLLECTION = 'REMOVE_COLLECTION'
export const GET_COLLECTIONS = 'GET_COLLECTIONS'
export const SET_COLLECTIONS = 'SET_COLLECTIONS'